"""LangGraph flow documentation for the dashboard."""

from __future__ import annotations

from config import DEFAULT_ASSUMPTIONS

_a = DEFAULT_ASSUMPTIONS

AGENT_FLOW = {
    "title": "LangGraph orchestration",
    "description": (
        "Each stage is a graph node in graph/workflow.py. "
        "In backtest mode, the deterministic engine mirrors the same flow without an LLM."
    ),
    "modes": {
        "backtest": "Deterministic engine — no LLM calls",
        "manual": "LLM configured via .env (LLM_PROVIDER/LLM_MODEL/LLM_BASE_URL/LLM_API_KEY) assists extraction, price explanation, and rejection messages",
    },
    "steps": [
        {
            "id": "extract",
            "backtest_step": "purchase",
            "label": "Extraction",
            "agent": "extract_node",
            "icon": "inbox",
            "summary": "Normalizes the travel booking into a typed structure (BookingFixture), optionally ingesting it from e-mail/PDF.",
            "inputs": ["booking (raw purchase JSON)", "or mailbox (e-mail + PDF/JSON attachments)"],
            "outputs": ["booking_model"],
            "logic": [
                "Validates required fields: booking_id, flight_date, origin/destination ICAO, values, passenger, and stay.",
                "E-mail path: MailboxSource -> DocumentExtractor (PDF) -> BookingExtractor -> BookingInput; missing mandatory fields stop the flow.",
                "Backtest mode: direct Pydantic validation of the fixture (no network, no LLM).",
                "Manual mode with a configured LLM (.env): the model extracts structured fields from the provided text/JSON.",
            ],
            "formulas": [],
            "rules": [],
            "module": "graph/workflow.py → extract_node",
            "next": ["price"],
        },
        {
            "id": "price",
            "backtest_step": "price",
            "label": "Pricing",
            "agent": "price_node",
            "icon": "calculator",
            "summary": "Computes PPR, pure rate, commercial rate, and premium from Technical Note No. 001.",
            "inputs": ["booking_model"],
            "outputs": ["pricing (PricingResult)"],
            "logic": [
                "SI (capital insured) = flight ticket + accommodation.",
                "Looks up cancellation and rain>10mm frequencies in the exposure table (route + year + month).",
                "Lookup: exact cell -> last year/month of the same route -> default 5% cancel / 15% rain; each step is recorded in fontes.",
                "Sets metodo=dados_completos, versao_nota_tecnica, sparsity_flag (n<500) and aviso (non-exact/fallback).",
                "Sparse destination: Haversine + γ similarity + IDW over K nearest anchor airports (pricing/geo,network,interpolation).",
                "GLM frequency (Poisson/Negative Binomial) and severity (Gamma/Log-Normal) models available in pricing/glm.py.",
                "Bühlmann-Straub credibility blends local experience and IDW when n<500 (Z=n/(n+K)).",
                "No local data: analogy path (Table 9 tools) estimates frequencies from UF/region, comparable routes and public search; the premium still comes from the formula.",
                "Commercial premium: θ∈[3%,12%] by interpolation spread, plus uncertainty loading and dynamic multiplier M.",
                "Rain trigger is strictly greater than 10.0 mm (10.0 exact does not trigger).",
            ],
            "formulas": [
                "PPR = (freq_cancel + freq_rain) × trip_loss",
                "trip_loss = ticket_value_brl + accommodation_value_brl",
                "Pure rate E[X] = PPR / SI",
                f"Commercial rate CR = E[X] × (1 + θ) / [1 − (c + d + d_a)]  (θ={_a.safety_margin:.0%}, c={_a.commission:.0%}, d={_a.profit:.0%}, d_a={_a.administrative_expense:.0%})",
                f"Premium = CR × SI, capped at {_a.max_premium_to_cs_ratio:.0%} of SI",
            ],
            "rules": [
                f"Premium cap: premium ≤ {_a.max_premium_to_cs_ratio:.0%} × capital insured",
            ],
            "module": "pricing/engine.py → PriceEngine.price",
            "next": ["underwrite"],
        },
        {
            "id": "underwrite",
            "backtest_step": "underwrite",
            "label": "Underwriting",
            "agent": "underwrite_node",
            "icon": "shield",
            "summary": "Recommendation over the current portfolio (route×month stock, event accumulation, appetite caps).",
            "inputs": ["booking_model", "pricing"],
            "outputs": ["underwriting (UnderwritingResult with recomendacao + carteira + pontos_a_conferir)"],
            "logic": [
                "Accumulates the persistent portfolio: premium/policies per route×month and capital per event (municipality + window).",
                "Recommendation: recusar (hard limit), revisao_humana (near a cap), seguir_ressalva (analogy/sparse), seguir.",
                "Human gate: when require_human_confirmation and the actuary confirmation is required, the flow stops at end_review.",
                "Manual mode: LLM rewrites the rejection reason in customer-facing language.",
            ],
            "formulas": [],
            "rules": [
                f"Minimum SI: BRL {_a.min_capital_insured_brl:,.0f}",
                f"Maximum SI: BRL {_a.max_capital_insured_brl:,.0f}",
                f"Premium exposure per route/month ≤ BRL {_a.max_premium_per_route_month_brl:,.0f}",
                f"Policies per route/month ≤ {_a.max_policies_per_route_month}",
                f"Event capital ≤ BRL {_a.max_capital_per_event_brl:,.0f}",
                f"Regional event capital (climatic region) ≤ BRL {_a.max_capital_per_region_event_brl:,.0f}",
                f"Sum of freq_cancel + freq_rain ≤ {_a.max_combined_event_frequency:.0%}",
                "Pure rate must be > 0",
            ],
            "module": "underwriting/rules.py → UnderwritingEngine.evaluate",
            "next": ["criteria", "end_rejected", "end_review"],
            "branches": {
                "criteria": "Risk accepted (no human gate)",
                "end_rejected": "Hard limit / reject",
                "end_review": "Human review required (analogy/near cap)",
            },
        },
        {
            "id": "criteria",
            "backtest_step": "criteria",
            "label": "Acceptance criteria",
            "agent": "criteria_node",
            "icon": "checklist",
            "summary": "Runs the isolated acceptance rules (R01–R08) and emits the verdict A/AC/RH/R/SI.",
            "inputs": ["booking_model", "portfolio"],
            "outputs": ["acceptance (AcceptanceResult: checks + veredito)"],
            "logic": [
                "consentimento/identidade; R06 risco futuro; R07 interesse legítimo; R01/R02 hotel e alta temporada; R03 malha aérea.",
                "índice meteorológico (com fallback); acúmulo (recheck); R08 fraude/sanções.",
                "Each rule answers pass/deny/review/info/conditional with evidence and the policy version.",
                "Verdict: A (all pass), AC (conditional adjustment, e.g. contracted fallback), RH (review), R (deny), SI (missing info).",
                "AC carries the list of conditions into the issued policy; A/AC proceed to issuance.",
                "Optional audit gate (audit_gate=True): A/AC go through governance/auditor.review; a block ends the flow without a policy.",
            ],
            "formulas": [],
            "rules": [
                "Hotel: diária > 130% da mediana (ou > R$ 3.000 sem alta temporada) → deny.",
                "Alta temporada excepcional → revisão humana (não deny automático).",
                "Sanção é vedação; alerta isolado de fraude não recusa sem comprovação.",
            ],
            "module": "criteria/verdict.py → evaluate_acceptance",
            "next": ["issue", "end_rejected", "end_review"],
            "branches": {
                "issue": "A / AC",
                "end_review": "RH / SI",
                "end_rejected": "R",
            },
        },
        {
            "id": "issue",
            "backtest_step": "issue",
            "label": "Issuance",
            "agent": "issue_node",
            "icon": "file",
            "summary": "Issues the policy (verdict A/AC), books the premium (Quadro 378) and PPNG = 100% of the premium.",
            "inputs": ["booking_model", "pricing", "acceptance (veredito)"],
            "outputs": ["policy (PolicyDocument with ppng/quadro_378/veredito)"],
            "logic": [
                "Generates a sequential policy_id: POL-YYYYMMDD-######.",
                "Records capital insured, premium, index/source/window/trigger, PPNG and Quadro 378.",
                "Coverage: effective_start = flight_date; effective_end = stay.end.",
            ],
            "formulas": [],
            "rules": ["Runs only when the acceptance verdict is A or AC"],
            "module": "policy/issuer.py → PolicyIssuer.issue",
            "next": ["monitor_claim"],
        },
        {
            "id": "monitor_claim",
            "backtest_step": "monitor",
            "label": "Monitoring & Claim",
            "agent": "monitor_claim_node",
            "icon": "radar",
            "summary": "Checks parametric triggers (cancellation and rain > 10 mm) and computes indemnity.",
            "inputs": ["booking_model", "policy", "pricing (frequencies)"],
            "outputs": ["claim (ClaimResult)"],
            "logic": [
                "Backtest: deterministic outcome via hash(booking_id) vs historical frequencies.",
                "Production: monitoring/index_monitor.py observes precipitation (>10mm strict) and flight status; reports are persisted in bases (storage/).",
                "Cancellation trigger: cancelled flight → pays flight + accommodation.",
                f"Rain trigger: precipitation > {_a.rain_threshold_mm:.0f} mm at destination → pays flight + accommodation.",
                "If both occur, indemnifies once (cancellation precedence).",
                "Trigger books Quadro 376 (aviso) and 377 (PSL=capital); settlement zeroes PSL and runs PPNG pro rata die.",
            ],
            "formulas": [
                "indemnity = ticket_value_brl + accommodation_value_brl (when a trigger fires)",
                "total_paid = cancel_paid + rain_paid (at most one trip loss)",
            ],
            "rules": [
                "No trigger → policy closed without payout",
                "Cancellation takes precedence over rain on the same event",
            ],
            "module": "monitoring/claims.py → ClaimsEngine.evaluate",
            "next": ["end"],
            "also_emits": "claim (separate event in the live backtest)",
        },
        {
            "id": "end_rejected",
            "backtest_step": "end",
            "label": "Close",
            "agent": "end_rejected_node / END",
            "icon": "flag",
            "summary": "Ends the flow — with an issued policy or with an underwriting rejection.",
            "inputs": ["result of previous stages"],
            "outputs": ["consolidated PolicyRecord", "accumulated metrics"],
            "logic": [
                "Accepted: emits a PolicyRecord with policy, premium, and any claim.",
                "Rejected: PolicyRecord without policy_id, with the underwriting reason.",
                "Backtest updates loss ratio, combined ratio, and premium/claim series.",
            ],
            "formulas": [
                "loss_ratio = claims_paid / premiums_issued",
                "combined_ratio = loss_ratio + loadings (PoC approximation)",
            ],
            "rules": [],
            "module": "backtest/engine.py → process_booking",
            "next": [],
        },
    ],
    "graph_edges": [
        {"from": "extract", "to": "price"},
        {"from": "price", "to": "underwrite"},
        {"from": "underwrite", "to": "criteria", "condition": "ACCEPTED"},
        {"from": "underwrite", "to": "end_rejected", "condition": "REJECTED"},
        {"from": "underwrite", "to": "end_review", "condition": "HUMAN_GATE"},
        {"from": "criteria", "to": "issue", "condition": "A / AC"},
        {"from": "criteria", "to": "end_review", "condition": "RH / SI"},
        {"from": "criteria", "to": "end_rejected", "condition": "R"},
        {"from": "issue", "to": "monitor_claim"},
        {"from": "monitor_claim", "to": "end"},
        {"from": "end_rejected", "to": "end"},
        {"from": "end_review", "to": "end"},
    ],
}
